config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :users
  
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    validates_presence_of(:email, :full_name, :location,:password)
    validates_confirmation_of :password
    validates_length_of :bio, :minium => 30, :allow_blank => false
    validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
  
    if @user.save
      redirect_to @user, notice: 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, :notice => 'Cadastro atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :location, :email, :password, :password_confirmation, :bio)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Colcho.net</h1>
<p>
Escolha uma das ações a seguir:
<ul>
<li><%= link_to "Cadastro", new_user_path %> </li>
<li><%= link_to "Visualizar quartos", rooms_path %> </li>
</ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colchonet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Title:</strong>
    <%= room.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= room.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>Infelizmente não foi possível completar a ação, pois o formulário possui os seguintes erros:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <p>
    <%= f.label :full_name %> <br />
    <%= f.text_field :full_name %>
  </p>
  <p>
    <%= f.label :location %> <br />
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :email %> <br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %> <br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %> <br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :bio %> <br />
    <%= f.text_area :bio %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editar perfil</h1>

<%= render "form", user: @user %>

<%= link_to "Voltar", @user %>

app/views/users/new.html.erb
<h1>Cadastro</h1>

<%= render "form", user: @user %>

<%= link_to "Voltar", root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %> </p>
<h2>Perfil: <%= @user.full_name %> </h2>
<ul>
<li>Localização: <%= @user.location %> </li>
<li>Bio: <%= @user.bio %> </li>
</ul>

<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>